### PR TITLE
Add Dropbox Scooter

### PR DESCRIPTION
**Pull request by spentacular**

### CODE REVIEW

**Comment by roybarber** [comment]
Is scooter not outdated with the push of Dropbox's new UI?

**Comment by alexpate** [comment]
Hmm not sure, as the author maybe @daneden could chime in on this one

**Comment by spentacular** [comment]
Agreed, it is outdated, but it's also one of the nicest in consistent naming conventions and structure.

**Comment by daneden** [comment]
Scooter was definitely more aesthetically relevant to Dropbox's old design language, but the principles it embodies are designed to outlive visual appearances and (to my knowledge) still form the basis of many of Dropbox's new components and styles.

**Comment by alexpate** [comment]
Sweet, thanks Dan. Let's get it added in then!

Thanks for the suggestion as well @spentacular

**Pull request merged**
